version: '3.5'

services:
  postgres:
    image: postgres:9.6
    container_name: jumpdigital
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      PGDATA: /data/postgres
      POSTGRES_MULTIPLE_DATABASES: ${DB_NAME:-local},${DB_USER:-postgres}:test
    volumes:
      - ./.docker/postgres:/data/postgres
      - ./psql-db.sh:/docker-entrypoint-initdb.d/psql-db.sh
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped
      
networks:
  postgres:
    driver: bridge
